server:
  port: 8000
spring:
  application:
    name: gateway
  cloud:
    consul:
      enabled: true
      discovery:
        query-passing: true
      config:
        data-key: application.yml
        prefixes: config
        format: yaml
        default-context: defaults
    gateway:
      routes:
        - id: rpsgame
          uri: lb://rpsgame/
          predicates:
            - Path=/results,/results/**
        - id: leaderboard
          uri: lb://leaderboard/
          predicates:
            - Path=/leaders,/stats
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "OPTIONS"
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET,POST
  config:
    import: "optional:consul:"